//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.18 at 04:47:14 PM CEST 
//


package smartcampus.service.esse3.jaxb.orari;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataSet" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Row" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="slot_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="prg_evento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="prg_evento_riga" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="des_evento_riga" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="des_partizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="des_tipo_att" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="dat_data_imp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="des_giorno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="des_persone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ora_inizio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ora_fine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="des_rf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="flg_weekend" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ext_aa_off_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ext_cds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ext_pds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ext_aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ext_ad_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ext_fat_part" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ext_dom_part" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="LocalEntityName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataSet"
})
@XmlRootElement(name = "WS")
public class WS {

    @XmlElement(name = "DataSet")
    protected List<WS.DataSet> dataSet;

    /**
     * Gets the value of the dataSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WS.DataSet }
     * 
     * 
     */
    public List<WS.DataSet> getDataSet() {
        if (dataSet == null) {
            dataSet = new ArrayList<WS.DataSet>();
        }
        return this.dataSet;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Row" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="slot_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="prg_evento" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="prg_evento_riga" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="des_evento_riga" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="des_partizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="des_tipo_att" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="dat_data_imp" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="des_giorno" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="des_persone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ora_inizio" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ora_fine" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="des_rf" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="flg_weekend" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ext_aa_off_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ext_cds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ext_pds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ext_aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ext_ad_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ext_fat_part" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ext_dom_part" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="LocalEntityName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "row"
    })
    public static class DataSet {

        @XmlElement(name = "Row")
        protected List<WS.DataSet.Row> row;
        @XmlAttribute(name = "LocalEntityName")
        protected String localEntityName;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WS.DataSet.Row }
         * 
         * 
         */
        public List<WS.DataSet.Row> getRow() {
            if (row == null) {
                row = new ArrayList<WS.DataSet.Row>();
            }
            return this.row;
        }

        /**
         * Gets the value of the localEntityName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalEntityName() {
            return localEntityName;
        }

        /**
         * Sets the value of the localEntityName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalEntityName(String value) {
            this.localEntityName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="slot_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="prg_evento" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="prg_evento_riga" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="des_evento_riga" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="des_partizione" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="des_tipo_att" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="dat_data_imp" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="des_giorno" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="des_persone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ora_inizio" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ora_fine" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="des_rf" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="flg_weekend" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ext_aa_off_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ext_cds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ext_pds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ext_aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ext_ad_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ext_fat_part" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ext_dom_part" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "slotId",
            "prgEvento",
            "prgEventoRiga",
            "desEventoRiga",
            "desPartizione",
            "desTipoAtt",
            "datDataImp",
            "desGiorno",
            "desPersone",
            "oraInizio",
            "oraFine",
            "desRf",
            "flgWeekend",
            "extAaOffId",
            "extCdsId",
            "extPdsId",
            "extAaOrdId",
            "extAdId",
            "extFatPart",
            "extDomPart"
        })
        public static class Row {

            @XmlElement(name = "slot_id", required = true)
            protected String slotId;
            @XmlElement(name = "prg_evento", required = true)
            protected String prgEvento;
            @XmlElement(name = "prg_evento_riga", required = true)
            protected String prgEventoRiga;
            @XmlElement(name = "des_evento_riga", required = true)
            protected String desEventoRiga;
            @XmlElement(name = "des_partizione", required = true)
            protected String desPartizione;
            @XmlElement(name = "des_tipo_att", required = true)
            protected String desTipoAtt;
            @XmlElement(name = "dat_data_imp", required = true)
            protected String datDataImp;
            @XmlElement(name = "des_giorno", required = true)
            protected String desGiorno;
            @XmlElement(name = "des_persone", required = true)
            protected String desPersone;
            @XmlElement(name = "ora_inizio", required = true)
            protected String oraInizio;
            @XmlElement(name = "ora_fine", required = true)
            protected String oraFine;
            @XmlElement(name = "des_rf", required = true)
            protected String desRf;
            @XmlElement(name = "flg_weekend", required = true)
            protected String flgWeekend;
            @XmlElement(name = "ext_aa_off_id", required = true)
            protected String extAaOffId;
            @XmlElement(name = "ext_cds_id", required = true)
            protected String extCdsId;
            @XmlElement(name = "ext_pds_id", required = true)
            protected String extPdsId;
            @XmlElement(name = "ext_aa_ord_id", required = true)
            protected String extAaOrdId;
            @XmlElement(name = "ext_ad_id", required = true)
            protected String extAdId;
            @XmlElement(name = "ext_fat_part", required = true)
            protected String extFatPart;
            @XmlElement(name = "ext_dom_part", required = true)
            protected String extDomPart;
            @XmlAttribute(name = "Num")
            protected String num;

            /**
             * Gets the value of the slotId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSlotId() {
                return slotId;
            }

            /**
             * Sets the value of the slotId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSlotId(String value) {
                this.slotId = value;
            }

            /**
             * Gets the value of the prgEvento property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrgEvento() {
                return prgEvento;
            }

            /**
             * Sets the value of the prgEvento property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrgEvento(String value) {
                this.prgEvento = value;
            }

            /**
             * Gets the value of the prgEventoRiga property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPrgEventoRiga() {
                return prgEventoRiga;
            }

            /**
             * Sets the value of the prgEventoRiga property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPrgEventoRiga(String value) {
                this.prgEventoRiga = value;
            }

            /**
             * Gets the value of the desEventoRiga property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDesEventoRiga() {
                return desEventoRiga;
            }

            /**
             * Sets the value of the desEventoRiga property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDesEventoRiga(String value) {
                this.desEventoRiga = value;
            }

            /**
             * Gets the value of the desPartizione property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDesPartizione() {
                return desPartizione;
            }

            /**
             * Sets the value of the desPartizione property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDesPartizione(String value) {
                this.desPartizione = value;
            }

            /**
             * Gets the value of the desTipoAtt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDesTipoAtt() {
                return desTipoAtt;
            }

            /**
             * Sets the value of the desTipoAtt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDesTipoAtt(String value) {
                this.desTipoAtt = value;
            }

            /**
             * Gets the value of the datDataImp property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatDataImp() {
                return datDataImp;
            }

            /**
             * Sets the value of the datDataImp property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatDataImp(String value) {
                this.datDataImp = value;
            }

            /**
             * Gets the value of the desGiorno property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDesGiorno() {
                return desGiorno;
            }

            /**
             * Sets the value of the desGiorno property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDesGiorno(String value) {
                this.desGiorno = value;
            }

            /**
             * Gets the value of the desPersone property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDesPersone() {
                return desPersone;
            }

            /**
             * Sets the value of the desPersone property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDesPersone(String value) {
                this.desPersone = value;
            }

            /**
             * Gets the value of the oraInizio property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOraInizio() {
                return oraInizio;
            }

            /**
             * Sets the value of the oraInizio property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOraInizio(String value) {
                this.oraInizio = value;
            }

            /**
             * Gets the value of the oraFine property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOraFine() {
                return oraFine;
            }

            /**
             * Sets the value of the oraFine property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOraFine(String value) {
                this.oraFine = value;
            }

            /**
             * Gets the value of the desRf property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDesRf() {
                return desRf;
            }

            /**
             * Sets the value of the desRf property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDesRf(String value) {
                this.desRf = value;
            }

            /**
             * Gets the value of the flgWeekend property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFlgWeekend() {
                return flgWeekend;
            }

            /**
             * Sets the value of the flgWeekend property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFlgWeekend(String value) {
                this.flgWeekend = value;
            }

            /**
             * Gets the value of the extAaOffId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExtAaOffId() {
                return extAaOffId;
            }

            /**
             * Sets the value of the extAaOffId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExtAaOffId(String value) {
                this.extAaOffId = value;
            }

            /**
             * Gets the value of the extCdsId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExtCdsId() {
                return extCdsId;
            }

            /**
             * Sets the value of the extCdsId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExtCdsId(String value) {
                this.extCdsId = value;
            }

            /**
             * Gets the value of the extPdsId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExtPdsId() {
                return extPdsId;
            }

            /**
             * Sets the value of the extPdsId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExtPdsId(String value) {
                this.extPdsId = value;
            }

            /**
             * Gets the value of the extAaOrdId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExtAaOrdId() {
                return extAaOrdId;
            }

            /**
             * Sets the value of the extAaOrdId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExtAaOrdId(String value) {
                this.extAaOrdId = value;
            }

            /**
             * Gets the value of the extAdId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExtAdId() {
                return extAdId;
            }

            /**
             * Sets the value of the extAdId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExtAdId(String value) {
                this.extAdId = value;
            }

            /**
             * Gets the value of the extFatPart property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExtFatPart() {
                return extFatPart;
            }

            /**
             * Sets the value of the extFatPart property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExtFatPart(String value) {
                this.extFatPart = value;
            }

            /**
             * Gets the value of the extDomPart property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getExtDomPart() {
                return extDomPart;
            }

            /**
             * Sets the value of the extDomPart property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setExtDomPart(String value) {
                this.extDomPart = value;
            }

            /**
             * Gets the value of the num property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNum() {
                return num;
            }

            /**
             * Sets the value of the num property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNum(String value) {
                this.num = value;
            }

        }

    }

}
