//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.17 at 04:31:13 PM CEST 
//


package smartcampus.service.esse3.jaxb.adlog;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataSet">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Row" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="aa_off_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ad_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="pds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="fat_part_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="dom_part_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="part_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ad_log_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="dom_part_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_part_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_aa_part_data_inizio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_aa_part_data_fine" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_aa_part_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_aa_part_durata" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="LocalEntityName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataSet"
})
@XmlRootElement(name = "WS")
public class WS {

    @XmlElement(name = "DataSet", required = true)
    protected WS.DataSet dataSet;

    /**
     * Gets the value of the dataSet property.
     * 
     * @return
     *     possible object is
     *     {@link WS.DataSet }
     *     
     */
    public WS.DataSet getDataSet() {
        return dataSet;
    }

    /**
     * Sets the value of the dataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link WS.DataSet }
     *     
     */
    public void setDataSet(WS.DataSet value) {
        this.dataSet = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Row" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="aa_off_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ad_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="pds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="fat_part_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="dom_part_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="part_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ad_log_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="dom_part_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_part_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_aa_part_data_inizio" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_aa_part_data_fine" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_aa_part_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_aa_part_durata" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="LocalEntityName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "row"
    })
    public static class DataSet {

        @XmlElement(name = "Row")
        protected List<WS.DataSet.Row> row;
        @XmlAttribute(name = "LocalEntityName")
        protected String localEntityName;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WS.DataSet.Row }
         * 
         * 
         */
        public List<WS.DataSet.Row> getRow() {
            if (row == null) {
                row = new ArrayList<WS.DataSet.Row>();
            }
            return this.row;
        }

        /**
         * Gets the value of the localEntityName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalEntityName() {
            return localEntityName;
        }

        /**
         * Sets the value of the localEntityName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalEntityName(String value) {
            this.localEntityName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="aa_off_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ad_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="pds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="fat_part_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="dom_part_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="part_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ad_log_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="dom_part_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_part_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_aa_part_data_inizio" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_aa_part_data_fine" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_aa_part_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_aa_part_durata" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cdsId",
            "aaOffId",
            "adId",
            "aaOrdId",
            "pdsId",
            "fatPartCod",
            "domPartCod",
            "partCod",
            "adLogId",
            "domPartDes",
            "p06PartDes",
            "p06AaPartDataInizio",
            "p06AaPartDataFine",
            "p06AaPartDes",
            "p06AaPartDurata"
        })
        public static class Row {

            @XmlElement(name = "cds_id", required = true)
            protected String cdsId;
            @XmlElement(name = "aa_off_id", required = true)
            protected String aaOffId;
            @XmlElement(name = "ad_id", required = true)
            protected String adId;
            @XmlElement(name = "aa_ord_id", required = true)
            protected String aaOrdId;
            @XmlElement(name = "pds_id", required = true)
            protected String pdsId;
            @XmlElement(name = "fat_part_cod", required = true)
            protected String fatPartCod;
            @XmlElement(name = "dom_part_cod", required = true)
            protected String domPartCod;
            @XmlElement(name = "part_cod", required = true)
            protected String partCod;
            @XmlElement(name = "ad_log_id", required = true)
            protected String adLogId;
            @XmlElement(name = "dom_part_des", required = true)
            protected String domPartDes;
            @XmlElement(name = "p06_part_des", required = true)
            protected String p06PartDes;
            @XmlElement(name = "p06_aa_part_data_inizio", required = true)
            protected String p06AaPartDataInizio;
            @XmlElement(name = "p06_aa_part_data_fine", required = true)
            protected String p06AaPartDataFine;
            @XmlElement(name = "p06_aa_part_des", required = true)
            protected String p06AaPartDes;
            @XmlElement(name = "p06_aa_part_durata", required = true)
            protected String p06AaPartDurata;
            @XmlAttribute(name = "Num")
            protected String num;

            /**
             * Gets the value of the cdsId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCdsId() {
                return cdsId;
            }

            /**
             * Sets the value of the cdsId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCdsId(String value) {
                this.cdsId = value;
            }

            /**
             * Gets the value of the aaOffId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAaOffId() {
                return aaOffId;
            }

            /**
             * Sets the value of the aaOffId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAaOffId(String value) {
                this.aaOffId = value;
            }

            /**
             * Gets the value of the adId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdId() {
                return adId;
            }

            /**
             * Sets the value of the adId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdId(String value) {
                this.adId = value;
            }

            /**
             * Gets the value of the aaOrdId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAaOrdId() {
                return aaOrdId;
            }

            /**
             * Sets the value of the aaOrdId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAaOrdId(String value) {
                this.aaOrdId = value;
            }

            /**
             * Gets the value of the pdsId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPdsId() {
                return pdsId;
            }

            /**
             * Sets the value of the pdsId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPdsId(String value) {
                this.pdsId = value;
            }

            /**
             * Gets the value of the fatPartCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFatPartCod() {
                return fatPartCod;
            }

            /**
             * Sets the value of the fatPartCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFatPartCod(String value) {
                this.fatPartCod = value;
            }

            /**
             * Gets the value of the domPartCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDomPartCod() {
                return domPartCod;
            }

            /**
             * Sets the value of the domPartCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDomPartCod(String value) {
                this.domPartCod = value;
            }

            /**
             * Gets the value of the partCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPartCod() {
                return partCod;
            }

            /**
             * Sets the value of the partCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPartCod(String value) {
                this.partCod = value;
            }

            /**
             * Gets the value of the adLogId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdLogId() {
                return adLogId;
            }

            /**
             * Sets the value of the adLogId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdLogId(String value) {
                this.adLogId = value;
            }

            /**
             * Gets the value of the domPartDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDomPartDes() {
                return domPartDes;
            }

            /**
             * Sets the value of the domPartDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDomPartDes(String value) {
                this.domPartDes = value;
            }

            /**
             * Gets the value of the p06PartDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06PartDes() {
                return p06PartDes;
            }

            /**
             * Sets the value of the p06PartDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06PartDes(String value) {
                this.p06PartDes = value;
            }

            /**
             * Gets the value of the p06AaPartDataInizio property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06AaPartDataInizio() {
                return p06AaPartDataInizio;
            }

            /**
             * Sets the value of the p06AaPartDataInizio property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06AaPartDataInizio(String value) {
                this.p06AaPartDataInizio = value;
            }

            /**
             * Gets the value of the p06AaPartDataFine property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06AaPartDataFine() {
                return p06AaPartDataFine;
            }

            /**
             * Sets the value of the p06AaPartDataFine property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06AaPartDataFine(String value) {
                this.p06AaPartDataFine = value;
            }

            /**
             * Gets the value of the p06AaPartDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06AaPartDes() {
                return p06AaPartDes;
            }

            /**
             * Sets the value of the p06AaPartDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06AaPartDes(String value) {
                this.p06AaPartDes = value;
            }

            /**
             * Gets the value of the p06AaPartDurata property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06AaPartDurata() {
                return p06AaPartDurata;
            }

            /**
             * Sets the value of the p06AaPartDurata property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06AaPartDurata(String value) {
                this.p06AaPartDurata = value;
            }

            /**
             * Gets the value of the num property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNum() {
                return num;
            }

            /**
             * Sets the value of the num property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNum(String value) {
                this.num = value;
            }

        }

    }

}
