//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.17 at 10:54:27 AM CEST 
//


package smartcampus.service.esse3.jaxb.ad;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataSet">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Row" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="p09_ad_pdsord_cds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p09_ad_pdsord_aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p09_ad_pdsord_aa_off_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p09_ad_pdsord_pds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p09_ad_pdsord_ad_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p09_ad_gen_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ad_gen_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p09_ad_pdsord_peso_ar" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p09_ad_cds_no_lez_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p09_ad_cds_cds_mut_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p09_ad_cds_ad_mut_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p09_ad_cds_aa_ord_mut_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p09_ad_cds_pds_mut_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cds_id_log" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="aa_ord_id_log" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="pds_id_log" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ad_id_log" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="LocalEntityName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataSet"
})
@XmlRootElement(name = "WS")
public class WS {

    @XmlElement(name = "DataSet", required = true)
    protected WS.DataSet dataSet;

    /**
     * Gets the value of the dataSet property.
     * 
     * @return
     *     possible object is
     *     {@link WS.DataSet }
     *     
     */
    public WS.DataSet getDataSet() {
        return dataSet;
    }

    /**
     * Sets the value of the dataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link WS.DataSet }
     *     
     */
    public void setDataSet(WS.DataSet value) {
        this.dataSet = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Row" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="p09_ad_pdsord_cds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p09_ad_pdsord_aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p09_ad_pdsord_aa_off_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p09_ad_pdsord_pds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p09_ad_pdsord_ad_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p09_ad_gen_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ad_gen_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p09_ad_pdsord_peso_ar" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p09_ad_cds_no_lez_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p09_ad_cds_cds_mut_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p09_ad_cds_ad_mut_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p09_ad_cds_aa_ord_mut_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p09_ad_cds_pds_mut_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cds_id_log" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="aa_ord_id_log" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="pds_id_log" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ad_id_log" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="LocalEntityName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "row"
    })
    public static class DataSet {

        @XmlElement(name = "Row")
        protected List<WS.DataSet.Row> row;
        @XmlAttribute(name = "LocalEntityName")
        protected String localEntityName;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WS.DataSet.Row }
         * 
         * 
         */
        public List<WS.DataSet.Row> getRow() {
            if (row == null) {
                row = new ArrayList<WS.DataSet.Row>();
            }
            return this.row;
        }

        /**
         * Gets the value of the localEntityName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalEntityName() {
            return localEntityName;
        }

        /**
         * Sets the value of the localEntityName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalEntityName(String value) {
            this.localEntityName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="p09_ad_pdsord_cds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p09_ad_pdsord_aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p09_ad_pdsord_aa_off_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p09_ad_pdsord_pds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p09_ad_pdsord_ad_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p09_ad_gen_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ad_gen_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p09_ad_pdsord_peso_ar" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p09_ad_cds_no_lez_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p09_ad_cds_cds_mut_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p09_ad_cds_ad_mut_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p09_ad_cds_aa_ord_mut_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p09_ad_cds_pds_mut_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cds_id_log" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="aa_ord_id_log" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="pds_id_log" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ad_id_log" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "p09AdPdsordCdsId",
            "p09AdPdsordAaOrdId",
            "p09AdPdsordAaOffId",
            "p09AdPdsordPdsId",
            "p09AdPdsordAdId",
            "p09AdGenCod",
            "adGenDes",
            "p09AdPdsordPesoAr",
            "p09AdCdsNoLezFlg",
            "p09AdCdsCdsMutId",
            "p09AdCdsAdMutId",
            "p09AdCdsAaOrdMutId",
            "p09AdCdsPdsMutId",
            "cdsIdLog",
            "aaOrdIdLog",
            "pdsIdLog",
            "adIdLog"
        })
        public static class Row {

            @XmlElement(name = "p09_ad_pdsord_cds_id", required = true)
            protected String p09AdPdsordCdsId;
            @XmlElement(name = "p09_ad_pdsord_aa_ord_id", required = true)
            protected String p09AdPdsordAaOrdId;
            @XmlElement(name = "p09_ad_pdsord_aa_off_id", required = true)
            protected String p09AdPdsordAaOffId;
            @XmlElement(name = "p09_ad_pdsord_pds_id", required = true)
            protected String p09AdPdsordPdsId;
            @XmlElement(name = "p09_ad_pdsord_ad_id", required = true)
            protected String p09AdPdsordAdId;
            @XmlElement(name = "p09_ad_gen_cod", required = true)
            protected String p09AdGenCod;
            @XmlElement(name = "ad_gen_des", required = true)
            protected String adGenDes;
            @XmlElement(name = "p09_ad_pdsord_peso_ar", required = true)
            protected String p09AdPdsordPesoAr;
            @XmlElement(name = "p09_ad_cds_no_lez_flg", required = true)
            protected String p09AdCdsNoLezFlg;
            @XmlElement(name = "p09_ad_cds_cds_mut_id", required = true)
            protected String p09AdCdsCdsMutId;
            @XmlElement(name = "p09_ad_cds_ad_mut_id", required = true)
            protected String p09AdCdsAdMutId;
            @XmlElement(name = "p09_ad_cds_aa_ord_mut_id", required = true)
            protected String p09AdCdsAaOrdMutId;
            @XmlElement(name = "p09_ad_cds_pds_mut_id", required = true)
            protected String p09AdCdsPdsMutId;
            @XmlElement(name = "cds_id_log", required = true)
            protected String cdsIdLog;
            @XmlElement(name = "aa_ord_id_log", required = true)
            protected String aaOrdIdLog;
            @XmlElement(name = "pds_id_log", required = true)
            protected String pdsIdLog;
            @XmlElement(name = "ad_id_log", required = true)
            protected String adIdLog;
            @XmlAttribute(name = "Num")
            protected String num;

            /**
             * Gets the value of the p09AdPdsordCdsId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP09AdPdsordCdsId() {
                return p09AdPdsordCdsId;
            }

            /**
             * Sets the value of the p09AdPdsordCdsId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP09AdPdsordCdsId(String value) {
                this.p09AdPdsordCdsId = value;
            }

            /**
             * Gets the value of the p09AdPdsordAaOrdId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP09AdPdsordAaOrdId() {
                return p09AdPdsordAaOrdId;
            }

            /**
             * Sets the value of the p09AdPdsordAaOrdId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP09AdPdsordAaOrdId(String value) {
                this.p09AdPdsordAaOrdId = value;
            }

            /**
             * Gets the value of the p09AdPdsordAaOffId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP09AdPdsordAaOffId() {
                return p09AdPdsordAaOffId;
            }

            /**
             * Sets the value of the p09AdPdsordAaOffId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP09AdPdsordAaOffId(String value) {
                this.p09AdPdsordAaOffId = value;
            }

            /**
             * Gets the value of the p09AdPdsordPdsId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP09AdPdsordPdsId() {
                return p09AdPdsordPdsId;
            }

            /**
             * Sets the value of the p09AdPdsordPdsId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP09AdPdsordPdsId(String value) {
                this.p09AdPdsordPdsId = value;
            }

            /**
             * Gets the value of the p09AdPdsordAdId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP09AdPdsordAdId() {
                return p09AdPdsordAdId;
            }

            /**
             * Sets the value of the p09AdPdsordAdId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP09AdPdsordAdId(String value) {
                this.p09AdPdsordAdId = value;
            }

            /**
             * Gets the value of the p09AdGenCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP09AdGenCod() {
                return p09AdGenCod;
            }

            /**
             * Sets the value of the p09AdGenCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP09AdGenCod(String value) {
                this.p09AdGenCod = value;
            }

            /**
             * Gets the value of the adGenDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdGenDes() {
                return adGenDes;
            }

            /**
             * Sets the value of the adGenDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdGenDes(String value) {
                this.adGenDes = value;
            }

            /**
             * Gets the value of the p09AdPdsordPesoAr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP09AdPdsordPesoAr() {
                return p09AdPdsordPesoAr;
            }

            /**
             * Sets the value of the p09AdPdsordPesoAr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP09AdPdsordPesoAr(String value) {
                this.p09AdPdsordPesoAr = value;
            }

            /**
             * Gets the value of the p09AdCdsNoLezFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP09AdCdsNoLezFlg() {
                return p09AdCdsNoLezFlg;
            }

            /**
             * Sets the value of the p09AdCdsNoLezFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP09AdCdsNoLezFlg(String value) {
                this.p09AdCdsNoLezFlg = value;
            }

            /**
             * Gets the value of the p09AdCdsCdsMutId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP09AdCdsCdsMutId() {
                return p09AdCdsCdsMutId;
            }

            /**
             * Sets the value of the p09AdCdsCdsMutId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP09AdCdsCdsMutId(String value) {
                this.p09AdCdsCdsMutId = value;
            }

            /**
             * Gets the value of the p09AdCdsAdMutId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP09AdCdsAdMutId() {
                return p09AdCdsAdMutId;
            }

            /**
             * Sets the value of the p09AdCdsAdMutId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP09AdCdsAdMutId(String value) {
                this.p09AdCdsAdMutId = value;
            }

            /**
             * Gets the value of the p09AdCdsAaOrdMutId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP09AdCdsAaOrdMutId() {
                return p09AdCdsAaOrdMutId;
            }

            /**
             * Sets the value of the p09AdCdsAaOrdMutId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP09AdCdsAaOrdMutId(String value) {
                this.p09AdCdsAaOrdMutId = value;
            }

            /**
             * Gets the value of the p09AdCdsPdsMutId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP09AdCdsPdsMutId() {
                return p09AdCdsPdsMutId;
            }

            /**
             * Sets the value of the p09AdCdsPdsMutId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP09AdCdsPdsMutId(String value) {
                this.p09AdCdsPdsMutId = value;
            }

            /**
             * Gets the value of the cdsIdLog property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCdsIdLog() {
                return cdsIdLog;
            }

            /**
             * Sets the value of the cdsIdLog property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCdsIdLog(String value) {
                this.cdsIdLog = value;
            }

            /**
             * Gets the value of the aaOrdIdLog property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAaOrdIdLog() {
                return aaOrdIdLog;
            }

            /**
             * Sets the value of the aaOrdIdLog property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAaOrdIdLog(String value) {
                this.aaOrdIdLog = value;
            }

            /**
             * Gets the value of the pdsIdLog property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPdsIdLog() {
                return pdsIdLog;
            }

            /**
             * Sets the value of the pdsIdLog property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPdsIdLog(String value) {
                this.pdsIdLog = value;
            }

            /**
             * Gets the value of the adIdLog property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAdIdLog() {
                return adIdLog;
            }

            /**
             * Sets the value of the adIdLog property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAdIdLog(String value) {
                this.adIdLog = value;
            }

            /**
             * Gets the value of the num property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNum() {
                return num;
            }

            /**
             * Sets the value of the num property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNum(String value) {
                this.num = value;
            }

        }

    }

}
