//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 12:03:41 PM CEST 
//


package smartcampus.service.esse3.jaxb.cds;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataSet">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Row" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="fac_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_rif_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="tipi_corso_tipo_corso_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_tipo_corso_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cdsord_aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="num_lingue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_sett_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cla_m_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cla_murst_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p07_cla_murst_cla_murst_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="test_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="num_posti_tot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_um_peso_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_tipo_spec_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="des_tipi_scuole_spec" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cdsord_valore_min" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_posti_stat_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="durata_anni" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="um_durata" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="durata_effettiva" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_web_view_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_web_immat_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p07_cla_ateneo_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_tipo_titit_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_ds_tipo_tit_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="aa_att_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="istat_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ciclo_istituito_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cdsord_stato_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cdsord_aa_ord_cess_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cdsord_data_var" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="url_sito_web" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                             &lt;element name="url_info_web" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p06_cds_norm_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p07_normativa_norm_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p07_normativa_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="LocalEntityName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataSet"
})
@XmlRootElement(name = "WS")
public class WS {

    @XmlElement(name = "DataSet", required = true)
    protected WS.DataSet dataSet;

    /**
     * Gets the value of the dataSet property.
     * 
     * @return
     *     possible object is
     *     {@link WS.DataSet }
     *     
     */
    public WS.DataSet getDataSet() {
        return dataSet;
    }

    /**
     * Sets the value of the dataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link WS.DataSet }
     *     
     */
    public void setDataSet(WS.DataSet value) {
        this.dataSet = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Row" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="fac_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_rif_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="tipi_corso_tipo_corso_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_tipo_corso_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cdsord_aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="num_lingue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_sett_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cla_m_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cla_murst_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p07_cla_murst_cla_murst_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="test_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="num_posti_tot" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_um_peso_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_tipo_spec_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="des_tipi_scuole_spec" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cdsord_valore_min" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_posti_stat_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="durata_anni" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="um_durata" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="durata_effettiva" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_web_view_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_web_immat_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p07_cla_ateneo_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_tipo_titit_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_ds_tipo_tit_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="aa_att_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="istat_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ciclo_istituito_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cdsord_stato_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cdsord_aa_ord_cess_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cdsord_data_var" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="url_sito_web" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                   &lt;element name="url_info_web" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p06_cds_norm_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p07_normativa_norm_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p07_normativa_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="LocalEntityName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "row"
    })
    public static class DataSet {

        @XmlElement(name = "Row")
        protected List<WS.DataSet.Row> row;
        @XmlAttribute(name = "LocalEntityName")
        protected String localEntityName;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WS.DataSet.Row }
         * 
         * 
         */
        public List<WS.DataSet.Row> getRow() {
            if (row == null) {
                row = new ArrayList<WS.DataSet.Row>();
            }
            return this.row;
        }

        /**
         * Gets the value of the localEntityName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalEntityName() {
            return localEntityName;
        }

        /**
         * Sets the value of the localEntityName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalEntityName(String value) {
            this.localEntityName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="fac_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_rif_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="tipi_corso_tipo_corso_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_tipo_corso_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cds_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cdsord_aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="num_lingue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_sett_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cla_m_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cla_murst_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p07_cla_murst_cla_murst_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="test_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="num_posti_tot" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_um_peso_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_tipo_spec_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="des_tipi_scuole_spec" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cdsord_valore_min" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_posti_stat_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="durata_anni" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="um_durata" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="durata_effettiva" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_web_view_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_web_immat_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p07_cla_ateneo_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_tipo_titit_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_ds_tipo_tit_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="aa_att_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="istat_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ciclo_istituito_flg" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cdsord_stato_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cdsord_aa_ord_cess_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cdsord_data_var" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="url_sito_web" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *         &lt;element name="url_info_web" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p06_cds_norm_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p07_normativa_norm_cod" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p07_normativa_des" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "facId",
            "p06CdsCod",
            "p06CdsDes",
            "p06CdsRifFlg",
            "tipiCorsoTipoCorsoDes",
            "p06CdsTipoCorsoCod",
            "cdsId",
            "p06CdsordAaOrdId",
            "numLingue",
            "p06CdsSettFlg",
            "claMId",
            "claMurstCod",
            "p07ClaMurstClaMurstDes",
            "testFlg",
            "numPostiTot",
            "p06CdsUmPesoCod",
            "p06CdsTipoSpecCod",
            "desTipiScuoleSpec",
            "p06CdsordValoreMin",
            "p06CdsPostiStatFlg",
            "durataAnni",
            "umDurata",
            "durataEffettiva",
            "p06CdsWebViewFlg",
            "p06CdsWebImmatFlg",
            "p07ClaAteneoCod",
            "p06CdsTipoTititCod",
            "p06CdsDsTipoTitDes",
            "aaAttId",
            "istatCod",
            "cicloIstituitoFlg",
            "p06CdsordStatoCod",
            "p06CdsordAaOrdCessId",
            "p06CdsordDataVar",
            "urlSitoWeb",
            "urlInfoWeb",
            "p06CdsNormId",
            "p07NormativaNormCod",
            "p07NormativaDes"
        })
        public static class Row {

            @XmlElement(name = "fac_id", required = true)
            protected String facId;
            @XmlElement(name = "p06_cds_cod", required = true)
            protected String p06CdsCod;
            @XmlElement(name = "p06_cds_des", required = true)
            protected String p06CdsDes;
            @XmlElement(name = "p06_cds_rif_flg", required = true)
            protected String p06CdsRifFlg;
            @XmlElement(name = "tipi_corso_tipo_corso_des", required = true)
            protected String tipiCorsoTipoCorsoDes;
            @XmlElement(name = "p06_cds_tipo_corso_cod", required = true)
            protected String p06CdsTipoCorsoCod;
            @XmlElement(name = "cds_id", required = true)
            protected String cdsId;
            @XmlElement(name = "p06_cdsord_aa_ord_id", required = true)
            protected String p06CdsordAaOrdId;
            @XmlElement(name = "num_lingue", required = true)
            protected String numLingue;
            @XmlElement(name = "p06_cds_sett_flg", required = true)
            protected String p06CdsSettFlg;
            @XmlElement(name = "cla_m_id", required = true)
            protected String claMId;
            @XmlElement(name = "cla_murst_cod", required = true)
            protected String claMurstCod;
            @XmlElement(name = "p07_cla_murst_cla_murst_des", required = true)
            protected String p07ClaMurstClaMurstDes;
            @XmlElement(name = "test_flg", required = true)
            protected String testFlg;
            @XmlElement(name = "num_posti_tot", required = true)
            protected String numPostiTot;
            @XmlElement(name = "p06_cds_um_peso_cod", required = true)
            protected String p06CdsUmPesoCod;
            @XmlElement(name = "p06_cds_tipo_spec_cod", required = true)
            protected String p06CdsTipoSpecCod;
            @XmlElement(name = "des_tipi_scuole_spec", required = true)
            protected String desTipiScuoleSpec;
            @XmlElement(name = "p06_cdsord_valore_min", required = true)
            protected String p06CdsordValoreMin;
            @XmlElement(name = "p06_cds_posti_stat_flg", required = true)
            protected String p06CdsPostiStatFlg;
            @XmlElement(name = "durata_anni", required = true)
            protected String durataAnni;
            @XmlElement(name = "um_durata", required = true)
            protected String umDurata;
            @XmlElement(name = "durata_effettiva", required = true)
            protected String durataEffettiva;
            @XmlElement(name = "p06_cds_web_view_flg", required = true)
            protected String p06CdsWebViewFlg;
            @XmlElement(name = "p06_cds_web_immat_flg", required = true)
            protected String p06CdsWebImmatFlg;
            @XmlElement(name = "p07_cla_ateneo_cod", required = true)
            protected String p07ClaAteneoCod;
            @XmlElement(name = "p06_cds_tipo_titit_cod", required = true)
            protected String p06CdsTipoTititCod;
            @XmlElement(name = "p06_cds_ds_tipo_tit_des", required = true)
            protected String p06CdsDsTipoTitDes;
            @XmlElement(name = "aa_att_id", required = true)
            protected String aaAttId;
            @XmlElement(name = "istat_cod", required = true)
            protected String istatCod;
            @XmlElement(name = "ciclo_istituito_flg", required = true)
            protected String cicloIstituitoFlg;
            @XmlElement(name = "p06_cdsord_stato_cod", required = true)
            protected String p06CdsordStatoCod;
            @XmlElement(name = "p06_cdsord_aa_ord_cess_id", required = true)
            protected String p06CdsordAaOrdCessId;
            @XmlElement(name = "p06_cdsord_data_var", required = true)
            protected String p06CdsordDataVar;
            @XmlElement(name = "url_sito_web", required = true)
            @XmlSchemaType(name = "anyURI")
            protected String urlSitoWeb;
            @XmlElement(name = "url_info_web", required = true)
            protected String urlInfoWeb;
            @XmlElement(name = "p06_cds_norm_id", required = true)
            protected String p06CdsNormId;
            @XmlElement(name = "p07_normativa_norm_cod", required = true)
            protected String p07NormativaNormCod;
            @XmlElement(name = "p07_normativa_des", required = true)
            protected String p07NormativaDes;
            @XmlAttribute(name = "Num")
            protected String num;

            /**
             * Gets the value of the facId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFacId() {
                return facId;
            }

            /**
             * Sets the value of the facId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFacId(String value) {
                this.facId = value;
            }

            /**
             * Gets the value of the p06CdsCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsCod() {
                return p06CdsCod;
            }

            /**
             * Sets the value of the p06CdsCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsCod(String value) {
                this.p06CdsCod = value;
            }

            /**
             * Gets the value of the p06CdsDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsDes() {
                return p06CdsDes;
            }

            /**
             * Sets the value of the p06CdsDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsDes(String value) {
                this.p06CdsDes = value;
            }

            /**
             * Gets the value of the p06CdsRifFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsRifFlg() {
                return p06CdsRifFlg;
            }

            /**
             * Sets the value of the p06CdsRifFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsRifFlg(String value) {
                this.p06CdsRifFlg = value;
            }

            /**
             * Gets the value of the tipiCorsoTipoCorsoDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipiCorsoTipoCorsoDes() {
                return tipiCorsoTipoCorsoDes;
            }

            /**
             * Sets the value of the tipiCorsoTipoCorsoDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipiCorsoTipoCorsoDes(String value) {
                this.tipiCorsoTipoCorsoDes = value;
            }

            /**
             * Gets the value of the p06CdsTipoCorsoCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsTipoCorsoCod() {
                return p06CdsTipoCorsoCod;
            }

            /**
             * Sets the value of the p06CdsTipoCorsoCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsTipoCorsoCod(String value) {
                this.p06CdsTipoCorsoCod = value;
            }

            /**
             * Gets the value of the cdsId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCdsId() {
                return cdsId;
            }

            /**
             * Sets the value of the cdsId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCdsId(String value) {
                this.cdsId = value;
            }

            /**
             * Gets the value of the p06CdsordAaOrdId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsordAaOrdId() {
                return p06CdsordAaOrdId;
            }

            /**
             * Sets the value of the p06CdsordAaOrdId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsordAaOrdId(String value) {
                this.p06CdsordAaOrdId = value;
            }

            /**
             * Gets the value of the numLingue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumLingue() {
                return numLingue;
            }

            /**
             * Sets the value of the numLingue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumLingue(String value) {
                this.numLingue = value;
            }

            /**
             * Gets the value of the p06CdsSettFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsSettFlg() {
                return p06CdsSettFlg;
            }

            /**
             * Sets the value of the p06CdsSettFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsSettFlg(String value) {
                this.p06CdsSettFlg = value;
            }

            /**
             * Gets the value of the claMId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClaMId() {
                return claMId;
            }

            /**
             * Sets the value of the claMId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClaMId(String value) {
                this.claMId = value;
            }

            /**
             * Gets the value of the claMurstCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClaMurstCod() {
                return claMurstCod;
            }

            /**
             * Sets the value of the claMurstCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClaMurstCod(String value) {
                this.claMurstCod = value;
            }

            /**
             * Gets the value of the p07ClaMurstClaMurstDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP07ClaMurstClaMurstDes() {
                return p07ClaMurstClaMurstDes;
            }

            /**
             * Sets the value of the p07ClaMurstClaMurstDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP07ClaMurstClaMurstDes(String value) {
                this.p07ClaMurstClaMurstDes = value;
            }

            /**
             * Gets the value of the testFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTestFlg() {
                return testFlg;
            }

            /**
             * Sets the value of the testFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTestFlg(String value) {
                this.testFlg = value;
            }

            /**
             * Gets the value of the numPostiTot property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumPostiTot() {
                return numPostiTot;
            }

            /**
             * Sets the value of the numPostiTot property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumPostiTot(String value) {
                this.numPostiTot = value;
            }

            /**
             * Gets the value of the p06CdsUmPesoCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsUmPesoCod() {
                return p06CdsUmPesoCod;
            }

            /**
             * Sets the value of the p06CdsUmPesoCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsUmPesoCod(String value) {
                this.p06CdsUmPesoCod = value;
            }

            /**
             * Gets the value of the p06CdsTipoSpecCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsTipoSpecCod() {
                return p06CdsTipoSpecCod;
            }

            /**
             * Sets the value of the p06CdsTipoSpecCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsTipoSpecCod(String value) {
                this.p06CdsTipoSpecCod = value;
            }

            /**
             * Gets the value of the desTipiScuoleSpec property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDesTipiScuoleSpec() {
                return desTipiScuoleSpec;
            }

            /**
             * Sets the value of the desTipiScuoleSpec property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDesTipiScuoleSpec(String value) {
                this.desTipiScuoleSpec = value;
            }

            /**
             * Gets the value of the p06CdsordValoreMin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsordValoreMin() {
                return p06CdsordValoreMin;
            }

            /**
             * Sets the value of the p06CdsordValoreMin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsordValoreMin(String value) {
                this.p06CdsordValoreMin = value;
            }

            /**
             * Gets the value of the p06CdsPostiStatFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsPostiStatFlg() {
                return p06CdsPostiStatFlg;
            }

            /**
             * Sets the value of the p06CdsPostiStatFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsPostiStatFlg(String value) {
                this.p06CdsPostiStatFlg = value;
            }

            /**
             * Gets the value of the durataAnni property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDurataAnni() {
                return durataAnni;
            }

            /**
             * Sets the value of the durataAnni property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDurataAnni(String value) {
                this.durataAnni = value;
            }

            /**
             * Gets the value of the umDurata property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUmDurata() {
                return umDurata;
            }

            /**
             * Sets the value of the umDurata property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUmDurata(String value) {
                this.umDurata = value;
            }

            /**
             * Gets the value of the durataEffettiva property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDurataEffettiva() {
                return durataEffettiva;
            }

            /**
             * Sets the value of the durataEffettiva property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDurataEffettiva(String value) {
                this.durataEffettiva = value;
            }

            /**
             * Gets the value of the p06CdsWebViewFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsWebViewFlg() {
                return p06CdsWebViewFlg;
            }

            /**
             * Sets the value of the p06CdsWebViewFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsWebViewFlg(String value) {
                this.p06CdsWebViewFlg = value;
            }

            /**
             * Gets the value of the p06CdsWebImmatFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsWebImmatFlg() {
                return p06CdsWebImmatFlg;
            }

            /**
             * Sets the value of the p06CdsWebImmatFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsWebImmatFlg(String value) {
                this.p06CdsWebImmatFlg = value;
            }

            /**
             * Gets the value of the p07ClaAteneoCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP07ClaAteneoCod() {
                return p07ClaAteneoCod;
            }

            /**
             * Sets the value of the p07ClaAteneoCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP07ClaAteneoCod(String value) {
                this.p07ClaAteneoCod = value;
            }

            /**
             * Gets the value of the p06CdsTipoTititCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsTipoTititCod() {
                return p06CdsTipoTititCod;
            }

            /**
             * Sets the value of the p06CdsTipoTititCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsTipoTititCod(String value) {
                this.p06CdsTipoTititCod = value;
            }

            /**
             * Gets the value of the p06CdsDsTipoTitDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsDsTipoTitDes() {
                return p06CdsDsTipoTitDes;
            }

            /**
             * Sets the value of the p06CdsDsTipoTitDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsDsTipoTitDes(String value) {
                this.p06CdsDsTipoTitDes = value;
            }

            /**
             * Gets the value of the aaAttId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAaAttId() {
                return aaAttId;
            }

            /**
             * Sets the value of the aaAttId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAaAttId(String value) {
                this.aaAttId = value;
            }

            /**
             * Gets the value of the istatCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIstatCod() {
                return istatCod;
            }

            /**
             * Sets the value of the istatCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIstatCod(String value) {
                this.istatCod = value;
            }

            /**
             * Gets the value of the cicloIstituitoFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCicloIstituitoFlg() {
                return cicloIstituitoFlg;
            }

            /**
             * Sets the value of the cicloIstituitoFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCicloIstituitoFlg(String value) {
                this.cicloIstituitoFlg = value;
            }

            /**
             * Gets the value of the p06CdsordStatoCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsordStatoCod() {
                return p06CdsordStatoCod;
            }

            /**
             * Sets the value of the p06CdsordStatoCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsordStatoCod(String value) {
                this.p06CdsordStatoCod = value;
            }

            /**
             * Gets the value of the p06CdsordAaOrdCessId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsordAaOrdCessId() {
                return p06CdsordAaOrdCessId;
            }

            /**
             * Sets the value of the p06CdsordAaOrdCessId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsordAaOrdCessId(String value) {
                this.p06CdsordAaOrdCessId = value;
            }

            /**
             * Gets the value of the p06CdsordDataVar property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsordDataVar() {
                return p06CdsordDataVar;
            }

            /**
             * Sets the value of the p06CdsordDataVar property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsordDataVar(String value) {
                this.p06CdsordDataVar = value;
            }

            /**
             * Gets the value of the urlSitoWeb property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrlSitoWeb() {
                return urlSitoWeb;
            }

            /**
             * Sets the value of the urlSitoWeb property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrlSitoWeb(String value) {
                this.urlSitoWeb = value;
            }

            /**
             * Gets the value of the urlInfoWeb property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrlInfoWeb() {
                return urlInfoWeb;
            }

            /**
             * Sets the value of the urlInfoWeb property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrlInfoWeb(String value) {
                this.urlInfoWeb = value;
            }

            /**
             * Gets the value of the p06CdsNormId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06CdsNormId() {
                return p06CdsNormId;
            }

            /**
             * Sets the value of the p06CdsNormId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06CdsNormId(String value) {
                this.p06CdsNormId = value;
            }

            /**
             * Gets the value of the p07NormativaNormCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP07NormativaNormCod() {
                return p07NormativaNormCod;
            }

            /**
             * Sets the value of the p07NormativaNormCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP07NormativaNormCod(String value) {
                this.p07NormativaNormCod = value;
            }

            /**
             * Gets the value of the p07NormativaDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP07NormativaDes() {
                return p07NormativaDes;
            }

            /**
             * Sets the value of the p07NormativaDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP07NormativaDes(String value) {
                this.p07NormativaDes = value;
            }

            /**
             * Gets the value of the num property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNum() {
                return num;
            }

            /**
             * Sets the value of the num property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNum(String value) {
                this.num = value;
            }

        }

    }

}
