//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.16 at 05:30:27 PM CEST 
//


package smartcampus.service.esse3.jaxb.pds;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataSet" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Row" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="cds_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="pds_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="cod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="p06_stati_ord_des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="web_immat_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="web_view_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="stato_cod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="obbl_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="tst_ta_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="comb_ta_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="comb_ta_des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="comb_ta_nota" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="tipo_titit_cod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="titit_cod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="stato_titolo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="dett_ta_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="titit_des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="tipi_tit_it_des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="rif_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="tipi_tit_it_livello" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="stato_richiesto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="voto_min" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="comb_ta_des_lin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="comb_ta_nota_des_lin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="abil_cons_sdr_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="abil_cons_ate_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="tit_univ_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="tit_it_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="tit_stra_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="LocalEntityName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataSet"
})
@XmlRootElement(name = "WS")
public class WS {

    @XmlElement(name = "DataSet")
    protected List<WS.DataSet> dataSet;

    /**
     * Gets the value of the dataSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WS.DataSet }
     * 
     * 
     */
    public List<WS.DataSet> getDataSet() {
        if (dataSet == null) {
            dataSet = new ArrayList<WS.DataSet>();
        }
        return this.dataSet;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Row" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="cds_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="pds_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="cod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="p06_stati_ord_des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="web_immat_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="web_view_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="stato_cod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="obbl_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="tst_ta_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="comb_ta_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="comb_ta_des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="comb_ta_nota" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="tipo_titit_cod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="titit_cod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="stato_titolo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="dett_ta_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="titit_des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="tipi_tit_it_des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="rif_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="tipi_tit_it_livello" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="stato_richiesto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="voto_min" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="comb_ta_des_lin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="comb_ta_nota_des_lin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="abil_cons_sdr_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="abil_cons_ate_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="tit_univ_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="tit_it_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="tit_stra_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="LocalEntityName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "row"
    })
    public static class DataSet {

        @XmlElement(name = "Row")
        protected List<WS.DataSet.Row> row;
        @XmlAttribute(name = "LocalEntityName")
        protected String localEntityName;

        /**
         * Gets the value of the row property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the row property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRow().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link WS.DataSet.Row }
         * 
         * 
         */
        public List<WS.DataSet.Row> getRow() {
            if (row == null) {
                row = new ArrayList<WS.DataSet.Row>();
            }
            return this.row;
        }

        /**
         * Gets the value of the localEntityName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalEntityName() {
            return localEntityName;
        }

        /**
         * Sets the value of the localEntityName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalEntityName(String value) {
            this.localEntityName = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="cds_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="aa_ord_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="pds_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="cod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="p06_stati_ord_des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="web_immat_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="web_view_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="stato_cod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="obbl_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="tst_ta_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="comb_ta_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="comb_ta_des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="comb_ta_nota" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="tipo_titit_cod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="titit_cod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="stato_titolo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="dett_ta_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="titit_des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="tipi_tit_it_des" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="rif_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="tipi_tit_it_livello" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="stato_richiesto" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="voto_min" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="comb_ta_des_lin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="comb_ta_nota_des_lin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="abil_cons_sdr_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="abil_cons_ate_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="tit_univ_flg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="tit_it_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="tit_stra_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Num" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cdsId",
            "aaOrdId",
            "pdsId",
            "cod",
            "des",
            "p06StatiOrdDes",
            "webImmatFlg",
            "webViewFlg",
            "statoCod",
            "obblFlg",
            "tstTaId",
            "combTaId",
            "combTaDes",
            "combTaNota",
            "tipoTititCod",
            "tititCod",
            "statoTitolo",
            "dettTaId",
            "tititDes",
            "tipiTitItDes",
            "rifFlg",
            "tipiTitItLivello",
            "statoRichiesto",
            "votoMin",
            "combTaDesLin",
            "combTaNotaDesLin",
            "abilConsSdrFlg",
            "abilConsAteFlg",
            "titUnivFlg",
            "titItId",
            "titStraId"
        })
        public static class Row {

            @XmlElement(name = "cds_id")
            protected String cdsId;
            @XmlElement(name = "aa_ord_id")
            protected String aaOrdId;
            @XmlElement(name = "pds_id")
            protected String pdsId;
            protected String cod;
            protected String des;
            @XmlElement(name = "p06_stati_ord_des")
            protected String p06StatiOrdDes;
            @XmlElement(name = "web_immat_flg")
            protected String webImmatFlg;
            @XmlElement(name = "web_view_flg")
            protected String webViewFlg;
            @XmlElement(name = "stato_cod")
            protected String statoCod;
            @XmlElement(name = "obbl_flg")
            protected String obblFlg;
            @XmlElement(name = "tst_ta_id")
            protected String tstTaId;
            @XmlElement(name = "comb_ta_id")
            protected String combTaId;
            @XmlElement(name = "comb_ta_des")
            protected String combTaDes;
            @XmlElement(name = "comb_ta_nota")
            protected String combTaNota;
            @XmlElement(name = "tipo_titit_cod")
            protected String tipoTititCod;
            @XmlElement(name = "titit_cod")
            protected String tititCod;
            @XmlElement(name = "stato_titolo")
            protected String statoTitolo;
            @XmlElement(name = "dett_ta_id")
            protected String dettTaId;
            @XmlElement(name = "titit_des")
            protected String tititDes;
            @XmlElement(name = "tipi_tit_it_des")
            protected String tipiTitItDes;
            @XmlElement(name = "rif_flg")
            protected String rifFlg;
            @XmlElement(name = "tipi_tit_it_livello")
            protected String tipiTitItLivello;
            @XmlElement(name = "stato_richiesto")
            protected String statoRichiesto;
            @XmlElement(name = "voto_min")
            protected String votoMin;
            @XmlElement(name = "comb_ta_des_lin")
            protected String combTaDesLin;
            @XmlElement(name = "comb_ta_nota_des_lin")
            protected String combTaNotaDesLin;
            @XmlElement(name = "abil_cons_sdr_flg")
            protected String abilConsSdrFlg;
            @XmlElement(name = "abil_cons_ate_flg")
            protected String abilConsAteFlg;
            @XmlElement(name = "tit_univ_flg")
            protected String titUnivFlg;
            @XmlElement(name = "tit_it_id")
            protected String titItId;
            @XmlElement(name = "tit_stra_id")
            protected String titStraId;
            @XmlAttribute(name = "Num")
            protected String num;

            /**
             * Gets the value of the cdsId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCdsId() {
                return cdsId;
            }

            /**
             * Sets the value of the cdsId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCdsId(String value) {
                this.cdsId = value;
            }

            /**
             * Gets the value of the aaOrdId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAaOrdId() {
                return aaOrdId;
            }

            /**
             * Sets the value of the aaOrdId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAaOrdId(String value) {
                this.aaOrdId = value;
            }

            /**
             * Gets the value of the pdsId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPdsId() {
                return pdsId;
            }

            /**
             * Sets the value of the pdsId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPdsId(String value) {
                this.pdsId = value;
            }

            /**
             * Gets the value of the cod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCod() {
                return cod;
            }

            /**
             * Sets the value of the cod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCod(String value) {
                this.cod = value;
            }

            /**
             * Gets the value of the des property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDes() {
                return des;
            }

            /**
             * Sets the value of the des property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDes(String value) {
                this.des = value;
            }

            /**
             * Gets the value of the p06StatiOrdDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP06StatiOrdDes() {
                return p06StatiOrdDes;
            }

            /**
             * Sets the value of the p06StatiOrdDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP06StatiOrdDes(String value) {
                this.p06StatiOrdDes = value;
            }

            /**
             * Gets the value of the webImmatFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWebImmatFlg() {
                return webImmatFlg;
            }

            /**
             * Sets the value of the webImmatFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWebImmatFlg(String value) {
                this.webImmatFlg = value;
            }

            /**
             * Gets the value of the webViewFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getWebViewFlg() {
                return webViewFlg;
            }

            /**
             * Sets the value of the webViewFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setWebViewFlg(String value) {
                this.webViewFlg = value;
            }

            /**
             * Gets the value of the statoCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatoCod() {
                return statoCod;
            }

            /**
             * Sets the value of the statoCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatoCod(String value) {
                this.statoCod = value;
            }

            /**
             * Gets the value of the obblFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getObblFlg() {
                return obblFlg;
            }

            /**
             * Sets the value of the obblFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setObblFlg(String value) {
                this.obblFlg = value;
            }

            /**
             * Gets the value of the tstTaId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTstTaId() {
                return tstTaId;
            }

            /**
             * Sets the value of the tstTaId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTstTaId(String value) {
                this.tstTaId = value;
            }

            /**
             * Gets the value of the combTaId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCombTaId() {
                return combTaId;
            }

            /**
             * Sets the value of the combTaId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCombTaId(String value) {
                this.combTaId = value;
            }

            /**
             * Gets the value of the combTaDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCombTaDes() {
                return combTaDes;
            }

            /**
             * Sets the value of the combTaDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCombTaDes(String value) {
                this.combTaDes = value;
            }

            /**
             * Gets the value of the combTaNota property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCombTaNota() {
                return combTaNota;
            }

            /**
             * Sets the value of the combTaNota property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCombTaNota(String value) {
                this.combTaNota = value;
            }

            /**
             * Gets the value of the tipoTititCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipoTititCod() {
                return tipoTititCod;
            }

            /**
             * Sets the value of the tipoTititCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipoTititCod(String value) {
                this.tipoTititCod = value;
            }

            /**
             * Gets the value of the tititCod property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTititCod() {
                return tititCod;
            }

            /**
             * Sets the value of the tititCod property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTititCod(String value) {
                this.tititCod = value;
            }

            /**
             * Gets the value of the statoTitolo property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatoTitolo() {
                return statoTitolo;
            }

            /**
             * Sets the value of the statoTitolo property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatoTitolo(String value) {
                this.statoTitolo = value;
            }

            /**
             * Gets the value of the dettTaId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDettTaId() {
                return dettTaId;
            }

            /**
             * Sets the value of the dettTaId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDettTaId(String value) {
                this.dettTaId = value;
            }

            /**
             * Gets the value of the tititDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTititDes() {
                return tititDes;
            }

            /**
             * Sets the value of the tititDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTititDes(String value) {
                this.tititDes = value;
            }

            /**
             * Gets the value of the tipiTitItDes property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipiTitItDes() {
                return tipiTitItDes;
            }

            /**
             * Sets the value of the tipiTitItDes property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipiTitItDes(String value) {
                this.tipiTitItDes = value;
            }

            /**
             * Gets the value of the rifFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRifFlg() {
                return rifFlg;
            }

            /**
             * Sets the value of the rifFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRifFlg(String value) {
                this.rifFlg = value;
            }

            /**
             * Gets the value of the tipiTitItLivello property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTipiTitItLivello() {
                return tipiTitItLivello;
            }

            /**
             * Sets the value of the tipiTitItLivello property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTipiTitItLivello(String value) {
                this.tipiTitItLivello = value;
            }

            /**
             * Gets the value of the statoRichiesto property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatoRichiesto() {
                return statoRichiesto;
            }

            /**
             * Sets the value of the statoRichiesto property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatoRichiesto(String value) {
                this.statoRichiesto = value;
            }

            /**
             * Gets the value of the votoMin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVotoMin() {
                return votoMin;
            }

            /**
             * Sets the value of the votoMin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVotoMin(String value) {
                this.votoMin = value;
            }

            /**
             * Gets the value of the combTaDesLin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCombTaDesLin() {
                return combTaDesLin;
            }

            /**
             * Sets the value of the combTaDesLin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCombTaDesLin(String value) {
                this.combTaDesLin = value;
            }

            /**
             * Gets the value of the combTaNotaDesLin property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCombTaNotaDesLin() {
                return combTaNotaDesLin;
            }

            /**
             * Sets the value of the combTaNotaDesLin property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCombTaNotaDesLin(String value) {
                this.combTaNotaDesLin = value;
            }

            /**
             * Gets the value of the abilConsSdrFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAbilConsSdrFlg() {
                return abilConsSdrFlg;
            }

            /**
             * Sets the value of the abilConsSdrFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAbilConsSdrFlg(String value) {
                this.abilConsSdrFlg = value;
            }

            /**
             * Gets the value of the abilConsAteFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAbilConsAteFlg() {
                return abilConsAteFlg;
            }

            /**
             * Sets the value of the abilConsAteFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAbilConsAteFlg(String value) {
                this.abilConsAteFlg = value;
            }

            /**
             * Gets the value of the titUnivFlg property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitUnivFlg() {
                return titUnivFlg;
            }

            /**
             * Sets the value of the titUnivFlg property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitUnivFlg(String value) {
                this.titUnivFlg = value;
            }

            /**
             * Gets the value of the titItId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitItId() {
                return titItId;
            }

            /**
             * Sets the value of the titItId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitItId(String value) {
                this.titItId = value;
            }

            /**
             * Gets the value of the titStraId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitStraId() {
                return titStraId;
            }

            /**
             * Sets the value of the titStraId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitStraId(String value) {
                this.titStraId = value;
            }

            /**
             * Gets the value of the num property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNum() {
                return num;
            }

            /**
             * Sets the value of the num property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNum(String value) {
                this.num = value;
            }

        }

    }

}
